Admin invoices cont
Freeing3092/little-esty-shop pull request #28
Opened 2022-11-08 03:35 UTC by ajpulzone

*I pulled down main prior to pull request 25 and resolved any merge conflicts

Pull request:
1.) Added drop down menu for invoice status selection, added functionality to updated that status with a button on the page.
2.) Added Admin Dashboard partial and applied that partial to all admin views
3.) Refactored all admin views to match the pictures we were given as guides.

2022-11-08 23:45 UTC, Freeing3092 requested changes
This  looks great. I like the addition of the partial to DRY up the views.

The only comment that I think should be addressed before merging to main relates to making the strong params a private method for security purposes.

2022-11-08 23:45 UTC, Freeing3092 commented on app/controllers/admin/invoices_controller.rb
> +    @invoice.save
This method works great, but I don't believe the `save` method is necessary here as `update` should save for us.

2022-11-08 23:45 UTC, Freeing3092 commented on app/controllers/admin/invoices_controller.rb
> +  def invoice_params
I believe we would want to specify this as a `private` method for security.

2022-11-09 00:21 UTC, ajpulzone commented
Pushed up branch with the requested changes made. AJP

2022-11-09 01:44 UTC, merged